#!/bin/bash
set -e

latest_runner_version=$(curl -I -v -s https://github.com/actions/runner/releases/latest 2>&1 | perl -ne 'next unless s/^< location: //; s{.*/v}{}; s/\s+//; print')

if [ -e /etc/image_runner_version ]; then
  image_runner_version=$(cat /etc/image_runner_version)
  if [ "$image_runner_version" = "$latest_runner_version" ]; then
    exit 0
  fi
  echo "Current runner version ($image_runner_version) is not up to date."
fi

echo "Installing latest version ($latest_runner_version)"
curl -sL "https://github.com/actions/runner/releases/download/v${latest_runner_version}/actions-runner-linux-x64-${latest_runner_version}.tar.gz" | tar xzvC /home/runner && \
    /home/runner/bin/installdependencies.sh && \
    apt-get -y clean && \
    rm -rf /var/cache/apt /var/lib/apt/lists/* /tmp/* /var/tmp/*

echo $latest_runner_version > /etc/image_runner_version
