#!/bin/bash

set -e

export CHECKOUT_PATH=/virtual-environments
export METADATA_FILE=/metadatafile
export HELPER_SCRIPTS="${CHECKOUT_PATH}"/images/linux/scripts/helpers
export SCRIPT_PATH="${CHECKOUT_PATH}"/images/linux/scripts/installers
export INSTALLER_SCRIPT_FOLDER="${CHECKOUT_PATH}"/images/linux/scripts/installers
git config --global advice.detachedHead false

if [ ! -d /virtual-environments ]; then
    git clone --branch "${VIRTUAL_ENVIRONMENT_VERSION}" --single-branch https://github.com/actions/virtual-environments "${CHECKOUT_PATH}"
fi

if [ ! -f /etc/apt/trusted.gpg.d/microsoft.gpg ]; then
    chmod +x "${CHECKOUT_PATH}"/images/linux/scripts/base/repos.sh
    "${CHECKOUT_PATH}"/images/linux/scripts/base/repos.sh
fi


if [ ! -f imagegeneration/toolset.json ]; then
    mkdir -p /imagegeneration/installers/ && cp "${CHECKOUT_PATH}"/images/linux/toolsets/toolset-"${UBUNTU_VERSION}".json /imagegeneration/installers/toolset.json
fi

if [ -z "$1" ]; then
    echo "You have the package you want to install."
    exit 1
fi
SCRIPT="${1}.sh"
if [ ! -f "${SCRIPT_PATH}/${SCRIPT}" ]; then
    echo "Package not available in the virtual environment."
    exit 1
fi

chmod +x ${SCRIPT_PATH}/"${SCRIPT}"
${SCRIPT_PATH}/"${SCRIPT}"

